name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm ci --no-audit --no-fund
    - name: Run tests and generate coverage information
      run: |
        npm run test
      env:
        CI: true
    - uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ./coverage/cobertura-coverage.xml
        format: markdown
        output: both
